CREATE DATABASE bmesi;
USE bmesi;
CREATE TABLE exam(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	answer char UNSIGNED NOT NULL
	);
CREATE TABLE login(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	registration INT UNSIGNED NOT NULL,
	delegate int UNSIGNED  NOT NULL
	);
