CREATE DATABASE bmesi;
USE bmesi;

CREATE TABLE quiz(
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	answer INT(1) UNSIGNED NOT NULL
);
CREATE TABLE login(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	registration INT(10) UNSIGNED NOT NULL,
	name VARCHAR(50) NOT NULL,
	over INT(1) DEFAULT 0 NOT NULL
);
CREATE TABLE user(
	registration INT(10) UNSIGNED NOT NULL,
	c_ans INT(3) UNSIGNED DEFAULT 0,
	w_ans INT(3) UNSIGNED DEFAULT 0
);
CREATE TABLE logout(
	registration INT(10) UNSIGNED NOT NULL,
	over INT(1) DEFAULT 0 NOT NULL,
	final_answer VARCHAR(50) ,
	Tstamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE img(
	id INT(3) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	image VARCHAR(50) NOT NULL
);
